name = "Recommender"
uuid = "f1dcbcfb-0b1d-45c0-883e-2edcfc1d4c23"
authors = ["yng87 <k.yanagi07@gmail.com> and contributors"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
MLJ = "add582a8-e3ab-11e8-2d5e-e98b27df1bc7"
MLJBase = "a7f614a8-145f-11e9-1d2a-a57a1082229d"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
TableOperations = "ab02a1b2-a7df-11e8-156e-fb1833f50b87"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
ZipFile = "a5390f91-8eb1-5f08-bee0-b1d1ffed6cea"

[compat]
CSV = "0.8"
DataFrames = "0.22, 1.1"
HTTP = "0.9"
MLJ = "0.16"
Parameters = "0.12"
TableOperations = "1.0"
Tables = "1.3"
ZipFile = "0.9"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
